name: Run tests on feature branch

on:
  push:
    branches-ignore:
      - master
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2 # Check out the code in the feature branch

      - name: Set up Python 3.10 # Set up Python 3.10
        uses: actions/setup-python@v2 # Set up Python 3.10
        with:
          python-version: '3.10'
'
      - name: Install dependencies
        run: make ci-setup

      - name: Run tests
        run: make ci-test